import pyodbc

sql_config = {
    'driver': 'ODBC Driver 18 for SQL Server',
    'server': 'localhost',
    'database': 'Darwin',
    'user': 'SA',
    'password': 'MTp070213.'
}
conn_str = (
    f"DRIVER={sql_config['driver']};"
    f"SERVER={sql_config['server']};"
    f"DATABASE={sql_config['database']};"
    f"UID={sql_config['user']};"
    f"PWD={sql_config['password']};"
    "TrustServerCertificate=yes;"
)

try:
    connection = pyodbc.connect(conn_str)
    print("Conexi√≥n exitosa")
    connection.close()
except pyodbc.Error as e:
    print("Error al conectar a la base de datos:", e)
